### ISSUE TITLE
More detailed documentation for running on a kubernetes cluster

### ISSUE THREAD

**Issue by Califax** [tkestack/gpu-admission#2]
Attempting to run gpu-admission on a kubernetes cluster doesn't appear to work right out of the box and it isn't described in the documentation to do it. 
I build the image from the docker file but the run command in it is:

CMD ["/bin/bash", "-c", "/usr/bin/gpu-admission --kubeconfig=/etc/kubernetes/kube-scheduler/kubeconfig --config=/etc/kubernetes/gpu-admission.config --address=0.0.0.0:3456 --v=$LOG_LEVEL --logtostderr=false --log-dir=/var/log/gpu-admission $EXTRA_FLAGS"]

Does this have to be run in the control plane? I am attempting to run this using the managed kubernetes services EKS and can't access the control plane nodes. To get around this I am running a second scheduler on a slave node. The config does not exist in /etc/kubernetes/gpu-admission.config when I deploy using the yaml file. Does the docker file need to be modified to create this directory and file on the node?

**Comment by mYmNeo** [comment]
> Attempting to run gpu-admission on a kubernetes cluster doesn't appear to work right out of the box and it isn't described in the documentation to do it.
> I build the image from the docker file but the run command in it is:
> 
> CMD ["/bin/bash", "-c", "/usr/bin/gpu-admission --kubeconfig=/etc/kubernetes/kube-scheduler/kubeconfig --config=/etc/kubernetes/gpu-admission.config --address=0.0.0.0:3456 --v=$LOG_LEVEL --logtostderr=false --log-dir=/var/log/gpu-admission $EXTRA_FLAGS"]
> 
> Does this have to be run in the control plane? I am attempting to run this using the managed kubernetes services EKS and can't access the control plane nodes. To get around this I am running a second scheduler on a slave node. The config does not exist in /etc/kubernetes/gpu-admission.config when I deploy using the yaml file. Does the docker file need to be modified to create this directory and file on the node?

If you want to run this app in a docker container, not a pod, you have to bind mount a volume to `/etc/kubernetes` which is described in `gpu-admission.yaml`. `gpu-admission.config` can be found in the directory `build`
