### ISSUE TITLE
some question about the architecture

### ISSUE THREAD

**Issue by JasonRD** [tkestack/gpu-admission#4]
1. why not use priority extender to help pick the best fit node?
2. is any feature to support the HA?

**Comment by mYmNeo** [comment]
> 1. why not use priority extender to help pick the best fit node?
> 2. is any feature to support the HA?

1. Priority can only give a score to a node, but there maybe other score functions affect the final node decision. In current architecture, we sometimes have to make gpu pods in the same node as much as possible.
2. At present, the answer is no, but we'll support in the future version
