### ISSUE TITLE
I couldn't understand how to run scheduler.

### ISSUE THREAD

**Issue by Servon-Lee** [tkestack/gpu-admission#7]
Hi there, I'm new to this field and I couldn't fully understand the README file. Could you give me some suggestions about some questions?

The first question is how to run scheduler with `--policy-config-file=XXX --use-legacy-policy-config=true`?

The second is what's `XXX` in `--policy-config-file=XXX`?

Any help would be appreciated!

**Comment by mYmNeo** [comment]
> Hi there, I'm new to this field and I couldn't fully understand the README file. Could you give me some suggestions about some questions?
> 
> The first question is how to run scheduler with `--policy-config-file=XXX --use-legacy-policy-config=true`?
> 
> The second is what's `XXX` in `--policy-config-file=XXX`?
> 
> Any help would be appreciated!

Read this article to help you understand [scheduler policy](https://kubernetes.io/docs/reference/scheduling/policies/)

**Comment by Servon-Lee** [comment]
Thanks for the material. I got to know the scheduler policy. What I want to do now is to carry out the scheduler extender.

But when I run `bin/gpu-admission --address=127.0.0.1:3456 --v=4 --config=build/gpu-admission.config --kubeconfig=/etc/kubernetes/admin.conf --policy-config-file=scheduler-policy-config.json --use-legacy-policy-config=true`, I got the error `unknown flag: --policy-config-file`. 

How can I fix it? Thanks in advance!

**Comment by mYmNeo** [comment]
> Thanks for the material. I got to know the scheduler policy. What I want to do now is to carry out the scheduler extender.
> 
> But when I run `bin/gpu-admission --address=127.0.0.1:3456 --v=4 --config=build/gpu-admission.config --kubeconfig=/etc/kubernetes/admin.conf --policy-config-file=scheduler-policy-config.json --use-legacy-policy-config=true`, I got the error `unknown flag: --policy-config-file`.
> 
> How can I fix it? Thanks in advance!

`--policy-config-file=XXX --use-legacy-policy-config=true` is for kube-scheduler not gpu-admission.

**Comment by Servon-Lee** [comment]
> `--policy-config-file=XXX --use-legacy-policy-config=true` is for kube-scheduler not gpu-admission.

I also tried `kube-scheduler --policy-config-file=scheduler-policy-config.json --use-legacy-policy-config=true`, but got the error: 
```
I0722 12:37:41.094767  428293 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0722 12:37:41.094833  428293 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0722 12:37:41.534391  428293 serving.go:313] Generated self-signed cert in-memory
failed to create listener: failed to listen on 0.0.0.0:10251: listen tcp 0.0.0.0:10251: bind: address already in use
````

**Comment by Servon-Lee** [comment]
> > `--policy-config-file=XXX --use-legacy-policy-config=true` is for kube-scheduler not gpu-admission.
> 
> I also tried `kube-scheduler --policy-config-file=scheduler-policy-config.json --use-legacy-policy-config=true`, but got the error:
> 
> ```
> I0722 12:37:41.094767  428293 registry.go:150] Registering EvenPodsSpread predicate and priority function
> I0722 12:37:41.094833  428293 registry.go:150] Registering EvenPodsSpread predicate and priority function
> I0722 12:37:41.534391  428293 serving.go:313] Generated self-signed cert in-memory
> failed to create listener: failed to listen on 0.0.0.0:10251: listen tcp 0.0.0.0:10251: bind: address already in use
> ```

@mYmNeo  Could you help me figure it out? Thanks in advance!

**Comment by Servon-Lee** [comment]
@mYmNeo Could you please offer more details?

**Comment by hyc-yuchen** [comment]
I have also encountered this problem. My version of k8s is 1.24.10

**Comment by hyc-yuchen** [comment]
Have you solved the problem?
I also encountered this problem, my k8s version is 1.24.10, what should I do?
